site_name: ライフサイエンス研究者のためのAIエージェントチュートリアル
site_description: 研究データベースを効率的に活用し、レベルに応じたAIエージェント活用法を学ぶ
site_author: Science Aid
site_url: https://fuku-inc.github.io/life-science-agent-tutorial/

repo_name: life-science-agent-tutorial
repo_url: https://github.com/fuku-inc/life-science-agent-tutorial

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え
  font:
    text: Noto Sans JP
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow

plugins:
  - search:
      lang: ja

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - ホーム: index.md
  - はじめに:
      - getting-started/index.md
      - 前提条件: getting-started/prerequisites.md
      - インストール:
          - getting-started/installation/index.md
          - Manus: getting-started/installation/manus.md
          - ChatGPT: getting-started/installation/chatgpt.md
          - Operator: getting-started/installation/operator.md
          - Claude Desktop: getting-started/installation/claude-desktop.md
          - Docker: getting-started/installation/docker.md
          - API Key設定: getting-started/installation/api-keys.md
  - チュートリアル:
      - tutorials/index.md
      - レベル1 - 既存エージェントの利用:
          - tutorials/01-try-agents/index.md
          - Manus:
              - tutorials/01-try-agents/manus/index.md
              - CO2固定を行う光合成細菌の系統・遺伝子解析: tutorials/01-try-agents/manus/photosynthesis-bacteria.md
          - Operator: 
              - tutorials/01-try-agents/operator/index.md
          - ChatGPT: 
              - tutorials/01-try-agents/chatgpt/index.md
      - レベル2 - MCPでツールを追加:
          - tutorials/02-mcp-server/index.md
          - MCPとは何か？: tutorials/02-mcp-server/what-is-mcp.md
          - Claude Desktop: 
              - tutorials/02-mcp-server/claude-desktop/index.md
              - PubMed検索: tutorials/02-mcp-server/claude-desktop/pubmed-search.md
          - ChatGPTカスタムコネクタ: tutorials/02-mcp-server/chatgpt-custom.md
      - レベル3 - エージェントシステム構築:
          - tutorials/03-build-agents/index.md
          - ADK: tutorials/03-build-agents/adk.md
          - AutoGen: tutorials/03-build-agents/autogen.md
      - レベル4 - マルチエージェントシステム:
          - tutorials/04-multi-agents/index.md
  - リソース:
      - resources/index.md
      - ライフサイエンスDB: resources/databases.md
      - ベンチマーク: resources/benchmarks.md
      - 学習資料: resources/learning-materials.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fuku-inc/life-science-agent-tutorial
  generator: false

copyright: Copyright &copy; 2025 Science Aid. All rights reserved.

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js